### ISSUE TITLE
Ardupilot Compilation Error due to Matlab Coder naming the sections variable after its type in the trajectoryBus.

### ISSUE THREAD

**Issue by EikeBremers** [iff-gsc/LADAC#1]
### Problem Descripion
When the default trajectoryBus initialization is called, the bus contains an array of type sections with the name sections.
In Matlab Simulink this is not a problem, but if the Matlab coder is used to generate the Ardupilot Code the code doesn't  compile.
This is because  the coder generates a the following data structure:

- struct of type sections containing the elements of one section
- struct of type trajectoryBus
-- containing among other things an array of type sections called sections

### Workaround
First possible workaround:
Changing the type of the struct in the generated code manually at the corresponding locations from sections to section.

Second possible workaround/solution:
- initializing the trajectoryBus as it is
- duplicating the bus sections under the name section
-- `section = sections`
- changing the type of the sections array to section:
--  `trajectoryBus.Elements(3).DataType = "section";`
-deleting the bus called sections
-changing the type in the corresponding libraries.

**Comment by fguecker** [comment]
Using the 'struct2slbus' function will resolve the Problem, as it names automatically all sub-buses with the additional ending xxxBus.

Replace `trajectoryBus = struct2bus_(traj_empty);` with `struct2slbus(traj_empty, 'trajectory');`

Currently, there is still a problem when `logical` are used in the structs, as these are called `boolean` under simulink and lead to a non-meaningful error message.
A HotFix has already been made and will be available within the next hour.
