### ISSUE TITLE
Add iterative trajectory calculation

### ISSUE THREAD

**Issue by fguecker** [iff-gsc/LADAC#33]

**Comment by fabian224** [comment]
This issure was solved with [ec80a80](https://github.com/iff-gsc/LADAC/commit/ec80a80b2e20d6428ce7792453ab9c9a7725ed68).

**Comment by fguecker** [comment]
This issure was solved with [ec80a80](https://github.com/iff-gsc/LADAC/commit/ec80a80b2e20d6428ce7792453ab9c9a7725ed68).
